### ISSUE TITLE
jsdom is no longer supported

### ISSUE THREAD

**Issue by jaredjj3** [stringsync/vexml#101]
While troubleshooting https://github.com/stringsync/vexml/pull/98, I came across https://github.com/vexflow/vexflow/issues/102, which states that jsdom will not be supported in Vexflow5.

Right now [lilypond.test.ts](https://github.com/stringsync/vexml/blob/33ff54aa0d328a8df6b392c1ae4d8ece544456eb/tests/integration/lilypond.test.ts) works by:

1. Render vexml in jsdom as SVG.
2. Attach SVG to an HTML page using puppeteer.
3. Use puppeteer to take a screenshot.

Instead, we need to:

1. Update the jest environment to build `vexml` and host it in memory.
2. Inject `<script>` tags that will load vexml and render an XML string.
3. Use puppeteer to take a screenshot.

I anticipate running into issues capturing errors thrown by the browser. I'm going to try to use `page.evaluate` to hook into the `pageerror` event and check the presence of errors in the test.

**Comment by rvilarl** [comment]
@jaredjj3 vexflow5 is not using jsdom in its testing. Nothing stops us from using it here.

**Comment by jaredjj3** [comment]
I reread the issue and it seems like as long as we're able to load the fonts at runtime we should be good to use jsdom, right?

**Comment by rvilarl** [comment]
This is right :)
