### ISSUE TITLE
Pianoplay with vexml:

### ISSUE THREAD

**Issue by rvilarl** [stringsync/vexml#118]
Two things are key for pianoplay:
- cursos, I use two. They allow to go next and back.
- information on the active notes at the cursor.

**Comment by jaredjj3** [comment]
The plan I have for this is to create something like a undirected graph out of `ScoreNavigationNode` objects. This will be derived from the [ScoreRendering](https://github.com/stringsync/vexml/blob/e1d05b0a98d1bf673cb3a25a7c8848d98d223652/src/rendering/score.ts#L14) object.

Think about navigating through a score with your keyboard on some existing notation software. You expect something different to be highlighted depending on what arrow key you press and the context.

A cursor can be thought of a graph crawler that just goes left and right based on the current time. It can fetch all the metadata of a voice entry by navigating up and down.

**Comment by rvilarl** [comment]
But not only based on the current time. In Pianoplay there are two cursors: one moves with the time and the other one moves when the user press the appropriated notes.

**Comment by jaredjj3** [comment]
Got it, I think what I have in mind will allow those cursors to coexist and you will be able to select a voice entry based on time, index, or position.

**Comment by jaredjj3** [comment]
@rvilarl, if #158 covers what you want, would you close this issue please?
