### ISSUE TITLE
MusicXML Player with vexml

### ISSUE THREAD

**Issue by infojunkie** [stringsync/vexml#122]
Like Pianoplay, I am also interested to use vexml to render MusicXML in my [player component](https://github.com/infojunkie/musicxml-player). Today, I support both OSMD and Verovio, and I find the latter more robust, although it is much harder to hack (C++ => wasm) so I would appreciate a simpler library. 

My basic requirements for integration:
- Ability to position cursor
- Ability to react on object (note) clicks / taps
- Ability to convert from measure number to timestamp and vice-versa

Happy to dig into this if there's interest from the maintainers here.

**Comment by jaredjj3** [comment]
Thanks for reaching out. I haven't heard of Verovio until today. I read through it a bit, and I agree it's dense, but it's definitely a great choice especially if performance is the goal.

The requirements you gave seem reasonable. FWIW, I achieved those things on top of OSMD in stringsync.com. The library is [here](https://github.com/stringsync/stringsync/tree/master/web/src/lib/MusicDisplay). I plan to bring the lessons learned from that project to `vexml`. Let me know if you have questions.

>Happy to dig into this if there's interest from the maintainers here.

At the moment, I consider the API and inner-workings unstable. Would you mind holding off until the library can successfully render full scores reliably?

Right now we're nailing smaller components in the [lilypond test suite](https://lilypond.org/doc/v2.23/input/regression/musicxml/collated-files.html). After that, we'll see how well we can render scores, which will inform how ready we are to work on more dynamic features.

**Comment by infojunkie** [comment]
Thanks for your reply. Sure, I'll keep and eye here and wait for a release.
