### ISSUE TITLE
Unable to run tests

### ISSUE THREAD

**Issue by infojunkie** [stringsync/vexml#123]
Running `yarn && yarn test`, I get:
```
[..]
warning " > babel-plugin-styled-components@2.0.7" has unmet peer dependency "styled-components@>= 2".
warning " > eslint-config-standard-with-typescript@21.0.1" has incorrect peer dependency "@typescript-eslint/eslint-plugin@^4.0.1".
warning " > eslint-config-standard-with-typescript@21.0.1" has incorrect peer dependency "eslint@^7.12.1".
warning " > eslint-config-standard-with-typescript@21.0.1" has incorrect peer dependency "typescript@^3.9 || ^4.0.0".
warning "eslint-config-standard-with-typescript > @typescript-eslint/parser@4.33.0" has incorrect peer dependency "eslint@^5.0.0 || ^6.0.0 || ^7.0.0".
warning "eslint-config-standard-with-typescript > eslint-config-standard@16.0.3" has incorrect peer dependency "eslint@^7.12.1".
warning " > eslint-plugin-promise@5.2.0" has incorrect peer dependency "eslint@^7.0.0".
error Could not write file "/vexml/yarn-error.log": "EACCES: permission denied, open '/vexml/yarn-error.log'"
error An unexpected error occurred: "EACCES: permission denied, mkdir '/vexml/node_modules'".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c yarn install' returned a non-zero code: 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
kratib@kindzadza:~/src/music/vexml$ ls -la
total 408
drwxrwxrwx   8 kratib kratib   4096 Oct  3 10:21 .
drwxrwxr-x 161 kratib kratib   4096 Sep 30 16:08 ..
[..]
drwxrwxr-x 509 kratib kratib  20480 Oct  3 10:21 node_modules
```

**Comment by jaredjj3** [comment]
It looks like there are two issues:

1. It looks like there's permission problem creating a `node_modules` directory. Did you try running `sudo yarn`?
2. You also have unmet peer dependencies, but I imagine this might be due to the first issue, since you're unable to install any packages.

**Comment by infojunkie** [comment]
When I run `yarn` from my host, I get the same warnings but the packages are installed. There are no issues with the permissions on the host, as per my previous bash dump (kratib is my username).

This permission error is occurring from within the docker build process. Looks like there's a problem with the Dockerfile and I'm surprised you're not getting the same - I'm running on Linux if that makes a difference.

**Comment by jaredjj3** [comment]
That's strange. It shouldn't make a difference that you're running on Linux. After all, that's one of the selling points of Docker. 

I saw in [vexml Github Action tests](https://github.com/stringsync/vexml/actions/runs/6388466989/job/17338343531#step:7:154) that they are having the same peer dependency issues as you, so I'll fix that. I must be having them when I build locally, but I must've been ignoring them. However, it doesn't make sense why the command succeeds while yours doesn't.

Some possible paths forward:

- Update the base image to `ghcr.io/puppeteer/puppeteer:latest` and see if that addresses it. Looks like the latest version is [21.3.6](https://github.com/puppeteer/puppeteer/pkgs/container/puppeteer/132397975?tag=21.3.6).

- Run outside of Docker: `yarn jest`. The snapshot tests may fail depending on how your machine renders the SVGs compared to the VM. The tests should output the paths where you can see the diffs. I'm going to improve the DX here soon in #121.

- Try seeing if the puppeteer/puppeteer image has something extra that's causing an issue. It looks like it's [built on top of node:18](https://github.com/puppeteer/puppeteer/blob/main/docker/Dockerfile). So try running this Dockerfile and let me know if the issues persist. Then we can narrow down our search space for this bug. I wonder if it's the `USER pptruser` line.

```dockerfile
FROM node:18
WORKDIR /vexml
COPY package.json .
COPY yarn.lock .
RUN yarn install
```

Sorry that this has been your first experience with the library, but I'm glad you brought up this issue so we can make it better for others.

**Comment by infojunkie** [comment]
> * Update the base image to `ghcr.io/puppeteer/puppeteer:latest` and see if that addresses it. Looks like the latest version is [21.3.6](https://github.com/puppeteer/puppeteer/pkgs/container/puppeteer/132397975?tag=21.3.6).

No change.

> * Run outside of Docker: `yarn jest`. The snapshot tests may fail depending on how your machine renders the SVGs compared to the VM. The tests should output the paths where you can see the diffs. I'm going to improve the DX here soon in [Allow image snapshot tests to be run outside of Docker #121](https://github.com/stringsync/vexml/issues/121).

Worked well, 8 failures.

> * Try seeing if the puppeteer/puppeteer image has something extra that's causing an issue. It looks like it's [built on top of node:18](https://github.com/puppeteer/puppeteer/blob/main/docker/Dockerfile). So try running this Dockerfile and let me know if the issues persist. Then we can narrow down our search space for this bug. I wonder if it's the `USER pptruser` line.

Built successfully.

I found this troubleshooting hint https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker - seems related, looks like you'd need to `chown -R pptruser:pptruser` a bunch of stuff.

**Comment by jaredjj3** [comment]
That's a very helpful hint. This is a bit hacky for now, but do you think we can assert your theory with the following Dockerfile?

```dockerfile
FROM ghcr.io/puppeteer/puppeteer:21.2.1

ENV VEXML_CANONICAL_TEST_ENV=true

WORKDIR /vexml

# Elevate temporarily to perform setup
# See https://github.com/puppeteer/puppeteer/blob/163394d7353d755e2b5ec47ffe56e2e869214860/docker/Dockerfile#L16
USER root

# Install dependencies.
COPY package.json .
COPY yarn.lock .
RUN yarn install

# Copy config.
COPY jest.config.js .
COPY babel.config.json .
COPY PuppeteerEnvironment.js .
COPY globalSetup.js .
COPY globalTeardown.js .
COPY jest.setup.js .

# Copy the code needed to run the dev server and tests.
COPY src src
COPY tests tests

# Run everything after as non-privileged user.
USER pptruser

# Run the test by default.
CMD [ "yarn", "jest" ]
```

**Comment by infojunkie** [comment]
Much better! Still not 100% working, though:

- After successfully installing the packages and building the Dockerfile, it complained with: 
```
$ docker run -it --rm -v ./src:/vexml/src -v ./tests:/vexml/tests vexml:latest yarn jest --runInBand
docker: Error response from daemon: create ./src: "./src" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
```
So I changed the line in `package.json` to 
```
    "test": "docker run -it --rm -v src:/vexml/src -v tests:/vexml/tests vexml:latest yarn jest --runInBand",
```

- The tests started running, but a few failed with the following error:
```
 RUNS  tests/integration/lilypond.test.ts
Error: EACCES: permission denied, unlink '/vexml/tests/integration/__image_snapshots__/__diff_output__/01a-Pitches-Pitches_900px-diff.png'
    at Object.unlinkSync (node:fs:1883:3)
    at Function.rimrafSync [as sync] (/vexml/node_modules/jest-image-snapshot/node_modules/rimraf/rimraf.js:314:17)
    at diffImageToSnapshot (/vexml/node_modules/jest-image-snapshot/src/diff-snapshot.js:236:12)
    at /vexml/node_modules/jest-image-snapshot/src/diff-process.js:27:20
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -13,
  syscall: 'unlink',
  code: 'EACCES',
  path: '/vexml/tests/integration/__image_snapshots__/__diff_output__/01a-Pitches-Pitches_900px-diff.png'
```

**Comment by jaredjj3** [comment]
Great, we're getting closer!

It looks like we're hitting subtle differences in our Docker engines (mine is 24.0.6 on macOS). Specifying volumes as absolute paths works on my host, so I'll update the repo to use that.

(I'm at the edge of my Linux/OS knowledge so I welcome any corrections to my misunderstandings)

Based on the troubleshooting we've done so far, it seems like `pptuser` doesn't have write permissions to `/vexml`. I wonder if your Docker engine executes the `USER` instruction differently than mine. My `umask` is 0022, which I think is standard:

```
% docker run -it vexml:latest /bin/bash -c "umask"
0022
```

If this is the theory, then I think we can validate that by removing the `USER pptruser` line in the Dockerfile and seeing if the tests run.

If the tests do run, then we should change the owner _and_ the permissions (?) of the `/vexml` dir and try again:

before the `USER pptruser` line:

```
RUN addgroup -S pptruser && adduser -S -G pptruser pptruser \
    && chown -R pptruser:pptruser /vexml
    && chmod -R 777 /vexml
```

---

Assuming running as root works, we have to make a tradeoff: security hygiene for maintainability.

We can continue running as root, but this is a bad security practice. The risk something in the test dependency tree does something malicious. I'd like to think this chance is low, but it's nonzero.

We can follow the principle of least privilege by carving out the exact permissions needed to run everything as `pptuser` and put that in the Dockerfile. This might raise an eyebrow or two for someone reading the Dockerfile, but that's easily mitigated with a good comment and maybe a link reference to something.

My vote is for the latter, but I'm open to other ideas you have. The problem is that I'm not able to reproduce your issues, so it'd be up to you to validate that whatever we land on works.

**Comment by infojunkie** [comment]
Yes, the permissions fixed it. Here's my full Dockerfile now:
```
FROM ghcr.io/puppeteer/puppeteer:21.2.1

ENV VEXML_CANONICAL_TEST_ENV=true

WORKDIR /vexml

# Elevate temporarily to perform setup
# See https://github.com/puppeteer/puppeteer/blob/163394d7353d755e2b5ec47ffe56e2e869214860/docker/Dockerfile#L16
USER root
RUN chown -R pptruser:pptruser /vexml \
    && chmod -R 777 /vexml
USER pptruser

# Install dependencies.
COPY package.json .
COPY yarn.lock .
RUN yarn install

# Copy config.
COPY jest.config.js .
COPY babel.config.json .
COPY PuppeteerEnvironment.js .
COPY globalSetup.js .
COPY globalTeardown.js .
COPY jest.setup.js .

# Copy the code needed to run the dev server and tests.
COPY src src
COPY tests tests

# Run the test by default.
CMD [ "yarn", "jest" ]
```
This, along with the change in `package.json` `test` line, passes all the tests for me :tada:

**Comment by jaredjj3** [comment]
Awesome! I'm glad that worked, feel free to make a PR (otherwise I'll just include it as a change in #129).

One thing worth calling out is that I think this risk exists using `chmod -R 777` (rwxrwxrwx):

>The risk is that something in the test dependency tree does something malicious as root and leverages the volumes to put something on your host. I'd like to think this chance is low, but it's nonzero.

I image Docker volumes inherently cause you to have the same permission modes you set in the image. The last thing I would ask of you is to see if `chmod -R 666` (rw-rw-rw-) still works.

Thanks again for all your help on this, I learned a lot.

**Comment by infojunkie** [comment]
`chmod 666` didn't work because it didn't fix the subdirectories - using `chmod ugoa+rwX` instead. This only sets the executable bit on directories, not files.
