### ISSUE TITLE
Create vexml site

### ISSUE THREAD

**Issue by jaredjj3** [stringsync/vexml#167]
## Requirements

**Make a simple site that allows users to render MusicXML documents. using `vexml`.**

- [x] It should be hosted on Github Pages.
- [x] It should provide a default rendered MusicXML document.
- [x] It should display rendering stats.
- [x] When the width of the `vexml` container changes, the score should re-render and update the rendering stats.
- [x] It may provide a MusicXML editor where changes are debounced. Errors are displayed nicely.
- [x] For now, it should the `master` branch as the `vexml` version. Maybe later, users can choose between `master` and releases.
- [ ] It has a link that allows users to easily file issues against. As a stretch goal, users should be able to easily export the rendered image, the MusicXML, and vexml version to the issue. Otherwise, make sure that the issue template requires them to include it.

## Hints

- This could probably be done in plain JavaScript. Try to avoid a whole application rendering pipeline for this.
- Nest everything under a `site` directory.
- WRT rendering stats, just do rendering time for now. Later, consider adding an object viewer that lets the user explore the resulting rendering tree.
- You might need to address #136 if you can't figure out how to compile the library with Github Pages' deployment pipeline. Then host a minified version on some CDN.
- Consider a simple component library like [Bootstrap](https://getbootstrap.com/) or [Tailwind ](https://tailwindcss.com/).

**Comment by jaredjj3** [comment]
@rvilarl, I'm going to work on this now so that it will be easier for you to do one-off tests, like how we did with the `dev` app. Let me know if there are specific features you'd like to see that I didn't cover.

**Comment by rvilarl** [comment]
@jaredjj3 this is already ambitious! You are improving vexflow a lot with vexml. Thanks!

**Comment by jaredjj3** [comment]
https://vexml.dev/ should rebuild and deploy to the [gh-pages](https://github.com/stringsync/vexml/tree/gh-pages) branch anytime something is pushed to `master`.

**Comment by jaredjj3** [comment]
@rvilarl, https://vexml.dev/ is in a usable state now. You can also use the dev version by running `yarn dev`. Let me know your feedback so far here. I'll make a GitHub issue template and see if it's possible to automatically attach data to it like a screenshot of the rendering and the error stack.

**Comment by jaredjj3** [comment]
If anyone has a better default MusicXML document than lilypond01a, feel free to suggest here.
