### ISSUE TITLE
[BUG] (v0.0.0): Voices in different parts are not formatted together

### ISSUE THREAD

**Issue by jaredjj3** [stringsync/vexml#181]
**Expected behavior**
When there are multiple parts, I expect notes to horizontally align based on what beat they start on.

**Actual behavior**
Each part renders independently of each other.

**Screenshot**

**vexml**
incorrect

<img width="924" alt="image" src="https://github.com/stringsync/vexml/assets/19232300/ab4a2001-a48a-40f2-ae57-318cea6b8147">

---

**MuseScore4**
correct

<img width="864" alt="image" src="https://github.com/stringsync/vexml/assets/19232300/e6ddd857-5fd1-48b1-8dd1-38e34201464c">

**Hints**

- [multi_part_formatting.zip](https://github.com/stringsync/vexml/files/13647789/multi_part_formatting.zip) (This is an .mxl file but I had to rename the ext for GitHub).
- Each system+part should already have the same number of measures through [rendering.Seed.split](https://github.com/stringsync/vexml/blob/7252f24d07e9e46d31da148bd0c1bacabc3c7314/src/rendering/seed.ts#L49).
- See [vexflow.System.format](https://github.com/0xfe/vexflow/blob/7e7eb97bf1580a31171302b3bd8165f057b692ba/src/system.ts#L238). As discussed in https://github.com/stringsync/vexml/pull/179#issuecomment-1849025310, we're not able to use `vexflow.System` without using `vexflow.Factory`, which is something we don't want to do. However, we can manually copy the formatting logic.
- You can use the Sarabande example from https://github.com/stringsync/vexml/pull/179#issue-2022746032, but there still might be other formatting issues that are separate from this bug report.

- [x] Attach the MusicXML file used to produce the bug.
- [x] Attach the error messages.
- [x] Include any `vexml` code references where the bug may be.

**Comment by rvilarl** [comment]
@jaredjj3 are you joining the voices of the different parts before calling format?
