### ISSUE TITLE
[BUG] (v0.0.0): Voices in a single part, but different staves are not formatted together

### ISSUE THREAD

**Issue by jaredjj3** [stringsync/vexml#182]
**Expected behavior**
When there is a single part with multiple staves, I expect notes to horizontally align based on what beat they start on.

**Actual behavior**
A clear and concise description of what actually happened.

**Screenshot**

**vexml**
incorrect (see measures 3 and 4)

<img width="975" alt="image" src="https://github.com/stringsync/vexml/assets/19232300/8ea3f3c3-49ca-4560-ac3b-8ea1cd03c410">

---

**MuseScore4**
correct

<img width="799" alt="image" src="https://github.com/stringsync/vexml/assets/19232300/23ac8498-238c-4cbd-9bf9-1745dba27ca9">

**Hints**

- This is likely closely related to #181. See the hints there.
- [multi_stave_single_part_formatting.zip](https://github.com/stringsync/vexml/files/13647939/multi_stave_single_part_formatting.zip) (This is an .mxl file but I had to rename the ext for GitHub).

- [x] Attach the MusicXML file used to produce the bug.
- [x] Attach the error messages.
- [x] Include any `vexml` code references where the bug may be.

**Comment by rvilarl** [comment]
@jaredjj3 same here, the voices of the different staves have to be joined.

**Comment by jaredjj3** [comment]
SG, that's what I plan to do after I ensure the measures are the same width.

**Comment by rvilarl** [comment]
If you are using the min width you also have to join them in advance. The alignment between voices in different staves and in different instrument do influence on the minimum width.

**Comment by jaredjj3** [comment]
That's a really good point. So when calculating minimum widths, I need to include all parts, join all their voices, then pre calculate the width. Right now, each MeasureFragment doesn't know anything about the other parts. I think there's a solution where I prescribe measure widths instead of calculating them twice at seed and render times.

**Comment by rvilarl** [comment]
I do not think that this is posible. Imagine one chord with many accidentals this will push the note to the right. The notes aligned with this one on other pparts will also have to be pushed even with no accidentals to keep the alingment.

**Comment by jaredjj3** [comment]
https://jsfiddle.net/fj6g9bxc/71/

This produces the correct result:

```ts
new Formatter().joinVoices([voice1]).formatToStave([voice1, voice2], stave1);
```

However, this produces the incorrect result:

```ts
new Formatter().joinVoices([voice1, voice2]).formatToStave([voice1, voice2], stave1);
```

It looks like I shouldn't join the voices before formatting to the stave, but this seems to conflict with the advice you gave me. What's the correct way to do this?

**Comment by rvilarl** [comment]
You have to join all the voices making one call to joinVoices per staff. The formatter needs to know if the voices are in the same staff which sets more constraints due to overlaps or on different ones where the notes can be aligned without considering overlap.

https://jsfiddle.net/7uy45swg/

**Comment by jaredjj3** [comment]
@rvilarl, this is very helpful, thank you. I have what I need to fix this now.
