### ISSUE TITLE
How to use this library

### ISSUE THREAD

**Issue by Daniel63656** [stringsync/vexml#234]
How do I use this library to create/inspect rendered musicXML files? From the readme there is some kind of template, but it is unclear where to place it and how to run it.
Thanks

**Comment by jaredjj3** [comment]
Thanks for reaching out! For now, you can copy-and-paste musicXML to https://vexml.dev. If I misunderstood what you wanted, please elaborate.

I haven't published the library yet since there are some features I wanted to get minimally viable first.

**Comment by Daniel63656** [comment]
Thanks that was what I was looking for.

I am trying to understand how this project relates to other projects like
open sheet music. I think you use a newer vexflow version? Are there other
differences?

I work on Optical Music Recognition (OMR) and need a way to visualize
results. MusicXML would work but ideally I would create the vexflow classes
directly from my own data model for music which I developed for Apps over
the last decade.
Maybe you can help me get started with that.

I noticed that in your code, cross beams (and therefore presumably voices
crossing staves) are not correctly displayed. I am not sure if vexflow
fixed this even.

Jared Johnson ***@***.***> schrieb am So., 29. Sept. 2024,
16:48:

**Comment by Daniel63656** [comment]
I found this to be a very fundamental modelling error in many music
libraries: not correctly modelling voice and staff as independent
coordinates of elements like chords and rests. This is certainly true for
vexflow, music21, open sheet music...

For me this is even more frustrating because in my model all of this is
possible. I even developed my own render engine and playback but this is
all in Java. I also found myself having to discontinue the development of
these aspects, as they are so complex and I wanted to focus on OMR. But now
I consistently find myself having to rely on tools that are a regression in
how they model music. I also translated my model from Java to python and
would need to get a final version that is more cross platform, maybe C++,
so I don't have to constantly reimplement it.
What is the endgame for these TypeScript libraries? I saw you often
implement typical application based features like cursors and playback. Is
this supposed to be later used in web applications, native apps? Also are
the classes constructed supposed to be used as an independent data model
(let's say from rendering)?

I think libraries like vexflow and your xml import would greatly benefit
from adopting a data model like the one I developed and refined over a
decade now.
Maybe you have time to meet in zoom or something.

Jared Johnson ***@***.***> schrieb am So., 29. Sept. 2024,
20:17:

**Comment by rvilarl** [comment]
As a side note, vexflow5 allows the notes in a voice to be in different staves. That was not allowed in the previous versions.

**Comment by Daniel63656** [comment]
Really? That's perfect. Is there an example somewhere?

**Comment by rvilarl** [comment]
See crossbeam tests in vexflow
https://github.com/vexflow/vexflow/blob/main/tests/crossbeam_tests.ts

![image](https://github.com/user-attachments/assets/1b06e499-34dc-4a7d-b662-a9682fdfb902)

Also test 43d in this library
![image](https://github.com/user-attachments/assets/71368cba-31bf-4b47-90d1-57fd24e13162)

**Comment by jaredjj3** [comment]
>What is the endgame for these TypeScript libraries?

Make music education web applications like https://michaelecke.com/pianoplay/#/home or https://stringsync.com

>Also are
the classes constructed supposed to be used as an independent data model for other tasks
(independent from rendering)?

I don't think so. I'm still trying to figure out what I want to expose. I'm wary that once I expose some part of the library, users will depend on it. I want to give users a high level way of interacting with a music sheet.

>I think libraries like vexflow and your xml import would greatly benefit
from adopting a data model like the one I developed and refined over a
decade now.

I'm curious. Where can I find this model?
