### ISSUE TITLE
Button to copy the code or even better a link to a jsfiddle with the code already there.

### ISSUE THREAD

**Issue by rvilarl** [stringsync/vexml#24]
@jaredjj3 It would be nice to have a button to copy the code or even better a link to a jsfiddle with the code already there :)

_Originally posted by @rvilarl in https://github.com/stringsync/vexml/issues/22#issuecomment-1095111274_

**Comment by rvilarl** [comment]
@jaredjj3 do you find that a good idea?

**Comment by jaredjj3** [comment]
I think this is a good idea and would serve your purposes. Maybe, I could do one even better: embed jsfiddle and prefill the code. However, I skimmed https://docs.jsfiddle.net/ and couldn't find anything about prefilling code. Do you know if this is possible?

**Comment by rvilarl** [comment]
this one perhaps:
https://docs.jsfiddle.net/api/display-a-fiddle-from-post

**Comment by rvilarl** [comment]
It comes with an example
http://jsfiddle.net/3Lwgk4c5/

**Comment by jaredjj3** [comment]
Perfect. That's what I was looking for. I'll see what I can do. Would you send me an example of the end result of what the fiddle should look like?

**Comment by rvilarl** [comment]
I will merge the open PR because the current master has some bugs related to code and post an example here after the gim.

**Comment by rvilarl** [comment]
There you are 

https://jsfiddle.net/ngtjx182/

**Comment by jaredjj3** [comment]
Thanks, I have reduced capacity for the next two weeks, but this seems like low effort and worth pursuing - especially since you expressed it will help.

**Comment by rvilarl** [comment]
@jaredjj3 I am wishing to see this one. The copy button alone would help a lot.

**Comment by jaredjj3** [comment]
I hear you loud and clear, I will try to get this done this week.

**Comment by rvilarl** [comment]
@jaredjj3 the code copy button makes my life much easier, thank you! I think that jsfiddle generation is not env required, we could close this issue if you agree.

**Comment by jaredjj3** [comment]
Thanks for the feedback, I'm glad it helped. The dev app already has enough dependencies and bottlenecks. I'm happy to close for now. Feel free to reopen if you think it'll make developing significantly more efficient.
