### ISSUE TITLE
Expected Vexflow test helper

### ISSUE THREAD

**Issue by jaredjj3** [stringsync/vexml#27]
This library's main concern is taking MusicXML and calling the right Vexflow APIs to render music notation. For unit tests, we only have to test that the correct Vexflow APIs get called. We don't have to test what actually gets rendered. In theory, the actual rendering is tested in the Vexflow library.

The purpose of this issue is to add a test helper that makes it easy to unit test this library.

**Comment by rvilarl** [comment]
Interesting, let us look how it develops :)

**Comment by jaredjj3** [comment]
After merging #90, I've gotten a lot wiser with this project. I don't think this is necessary anymore. VexFlow is incredibly complex. If there are certain properties on VexFlow objects we want to assert, we can do that directly. However, I think it's just better to test the actual rendering since that's what we care about in the end.
