### ISSUE TITLE
output code is getting too complex.

### ISSUE THREAD

**Issue by rvilarl** [stringsync/vexml#29]
You would need to define notestruct then. I will leave it as it. I think we have to look at the output code anyway, it is getting too complex.

_Originally posted by @rvilarl in https://github.com/stringsync/vexml/pull/25#discussion_r851241649_

**Comment by jaredjj3** [comment]
I recommend waiting until our implementation is more stable before re-pursuing this. Once that happens, we can switch back to your original idea of just printing plain strings. One of the sources of complexity is the shared state in the `renderer` implementation. We need to isolate the data better.

**Comment by rvilarl** [comment]
I agree. Worst case we will end up using t.literal only.
