### ISSUE TITLE
Next features: Accidentals, Clefs, scores on several lines

### ISSUE THREAD

**Issue by rvilarl** [stringsync/vexml#31]
I believe the next features should be to support all the combinations present in the tests for:
- accidentals, including parenthesis
- clefs

Support multiple lines for scores.

@jaredjj3 do you have another preference?

**Comment by rvilarl** [comment]
#32  & #33 address the first two points

**Comment by jaredjj3** [comment]
After these features, we really need to take a step back and think of a more maintainable approach. I'll start thinking about this more.
