### ISSUE TITLE
Render snapshots and image diffing

### ISSUE THREAD

**Issue by jaredjj3** [stringsync/vexml#38]
@rvilarl, I accidentally pushed to `master`, so I'm just making an issue to let you know about a new dev feature. Please close this if you don't have any ideas to change the feature.

You can snapshot `vexml` renderings and it'll automatically diff the historical rendering against a current one. Snapshots are tracked in https://github.com/stringsync/vexml/tree/master/dev/public/snapshots, so you should only take a snapshot if you know that the current rendering is correct. It does this lazily when you open the "diff" tab, so you don't have to worry about this slamming your machine's resources when you open the index.

https://user-images.githubusercontent.com/19232300/163743304-d716d0a3-0e5e-416d-b18d-59e2e4dd53c0.mov

**Comment by rvilarl** [comment]
@jaredjj3 this is a very nice feature, thanks! Would ti be possible to show in the index with a second icon which tests do not match 100%? I mean to avoid having to look into everyone manually to look for differences.
And do not forget #24 :)

**Comment by rvilarl** [comment]
Perhaps two general buttoms in the index one to take an overall snapshot and one to get a stats of failed diffs (not 100% identical) to avoid running this all the time.

**Comment by jaredjj3** [comment]
Sure thing. I think you're looking for something like this and a "snapshot all" button on the index?

![image](https://user-images.githubusercontent.com/19232300/163822781-26a6109f-e81d-4da4-bd62-76f055d0795e.png)

I need to iron a few things out. I don't think I should treat the statuses of `vexml` and snapshot comparisons separately. I can have something ready by tomorrow.
