### ISSUE TITLE
Chords

### ISSUE THREAD

**Issue by rvilarl** [stringsync/vexml#42]
It is quite inconvenient that the chords have to be provided alphabeticaly ordered when this is not the case in Music XML. I am terying to resolve this in VexFlow but it by far more complicted than expected.
If I do not resolve that the processing of the chords' accidentals, ... will be very complicated.

**Comment by rvilarl** [comment]
There is already a PR in VexFlow addressing the order of Chords
https://github.com/0xfe/vexflow/pull/1387

**Comment by jaredjj3** [comment]
I agree with your approach. Thanks for fixing that, your work is very valuable to the community!

**Comment by acidjunk** [comment]
Keep up the good work; this looks very promising.

**Comment by jaredjj3** [comment]
Thanks for the positive feedback @acidjunk! Let me know if you'd like to get involved in what we're doing.
