### ISSUE TITLE
Passacaglia

### ISSUE THREAD

**Issue by rvilarl** [stringsync/vexml#54]
@jaredjj3 I will now give support to `print` and make additional changes to make sure that passacaglia looks fine. We will see what comes out of this experiment. :)

**Comment by jaredjj3** [comment]
Sounds good, let me know if you run into any blockers.

**Comment by jaredjj3** [comment]
It looks promising. Wishing you the best of luck! :)

**Comment by rvilarl** [comment]
Vexml is now adapted to the vexflow PR above (I found one VexFlow bug with I pushed today). Passacaglia is now looking good! Once https://github.com/0xfe/vexflow/pull/1409 is merged I will make a PR.
![passacaglia](https://user-images.githubusercontent.com/22865285/174476977-52fab12a-8109-4455-a66f-c769fc86abd3.png)

**Comment by jaredjj3** [comment]
@rvilarl it looks great! Would you elaborate on how https://github.com/0xfe/vexflow/pull/1409 affects this library?

**Comment by rvilarl** [comment]
Hi @jaredjj3 with this library and the first used case that we have "Check compliance to the Innoficial MusicXML Test Suite" 
On the way gaps (missing noteheads https://github.com/0xfe/vexflow/pull/1401), desing problems  and bugs in VexFlow are made evident and I am trying to resolve them in parallel.

https://github.com/0xfe/vexflow/pull/1409 is resolving a design problem and a bug:
- without this PR voices can not move between staves, which is indeed a valid use case. `system` in VexFlow is not allowing that and I had to avoid its usage in the current state of this library. Once https://github.com/0xfe/vexflow/pull/1409 is merged I will make a PR using `system`which reduces the complexity in this library.
- I also discussed with Aaron on how to use `system` with `autowidth` in https://github.com/0xfe/vexflow/issues/1411. I have extended the interface of `System` with get/setX & get/setY to simplify this use case. Doing that I discovered a bug, `system` was not providing the recalculated width on its bounding box when `autowidth` was used.

 (@0xfe @ronyeh @AaronDavidNewman @mscuthbert @schmidTU  this might be of your interest)

**Comment by rvilarl** [comment]
@jaredjj3 I still did not get the PR in vexflow through :(

**Comment by jaredjj3** [comment]
@rvilarl does it make sense to shelve for now, or does this work block what you wanted to do next?

**Comment by rvilarl** [comment]
@jaredjj3 I am trying to progress with small chunks, if I get stuck again, I will choose a next item. I wan to get his compatibility check done to the end :)
