### ISSUE TITLE
Missing: Brackets

### ISSUE THREAD

**Issue by rvilarl** [stringsync/vexml#61]

**Comment by jaredjj3** [comment]
@rvilarl would you clarify what is needed here? If I were to guess, I think you're referring to [braces](https://github.com/stringsync/vexml/blob/master/tests/integration/__image_snapshots__/02e-Rests-NoType_900px.png), which `vexml` does handle for multistave parts.

**Comment by rvilarl** [comment]
This is right, I just saw them in #115
