### ISSUE TITLE
Missing: Metronome marks

### ISSUE THREAD

**Issue by rvilarl** [stringsync/vexml#62]

**Comment by jaredjj3** [comment]
This will be implemented in [31c-MetronomeMarks.xml](https://lilypond.org/doc/v2.23/input/regression/musicxml/collated-files.html).

**Comment by jaredjj3** [comment]
I'm working on this next.

**Comment by jaredjj3** [comment]
@rvilarl, in the lilypond example, which marks would you consider the most commonly used?

![image](https://github.com/stringsync/vexml/assets/19232300/90c2f2c5-0d82-4db9-a994-7a6bb4d047a9)

**Comment by rvilarl** [comment]
Those with note equal number

**Comment by jaredjj3** [comment]
This is how `vexml` renders the lilypond test, which I think covers most cases.

<img width="803" alt="image" src="https://github.com/stringsync/vexml/assets/19232300/946ed9b7-f718-480c-8889-704f9acabf9e">

**Comment by jaredjj3** [comment]
Ah, I didn't pay close attention to the beat values — they seem wrong. I'm going to take a closer look. Sorry about the noise.
