### ISSUE TITLE
Challenge: Generate code for Joplin - Gladiolus Rag

### ISSUE THREAD

**Issue by rvilarl** [stringsync/vexml#78]
The good news: no crash reading the XML file.
The challenge: quite a few things to fix.

![image](https://user-images.githubusercontent.com/22865285/212888556-bdd2c253-5362-4244-8086-69c75041e59f.png)

**Comment by rvilarl** [comment]
Our target :)

![image](https://user-images.githubusercontent.com/22865285/212888811-569173d4-ecc4-4e8d-971f-cef1808cf05c.png)

**Comment by jaredjj3** [comment]
I like this approach. It gives us concrete bugs to work on. The cross-staff notations are particularly interesting.

**Comment by jaredjj3** [comment]
@rvilarl, would you attach the MusicXML file somewhere in this issue please?

**Comment by rvilarl** [comment]
The score is this one https://musescore.com/user/58480/scores/1749906

**Comment by rvilarl** [comment]
@jaredjj3 the score produces this fault at https://vexml.dev/
 
[Gladiolus_Rag__Scott_Joplin__1907.zip](https://github.com/stringsync/vexml/files/13811849/Gladiolus_Rag__Scott_Joplin__1907.zip)


17:12:14.620 (1296px) Error: [RuntimeError] BadArguments: Too few notes for beam. at new sf (https://vexml.dev/assets/index-e7Ei05G8.js:60:246688) at Wo.render (https://vexml.dev/assets/index-e7Ei05G8.js:60:1213988) at https://vexml.dev/assets/index-e7Ei05G8.js:60:1224036 at Array.map (<anonymous>) at Jh.render (https://vexml.dev/assets/index-e7Ei05G8.js:60:1224027) at Zs.render (https://vexml.dev/assets/index-e7Ei05G8.js:61:5105) at mr.render (https://vexml.dev/assets/index-e7Ei05G8.js:63:174) at https://vexml.dev/assets/index-e7Ei05G8.js:63:7625 at Dc (https://vexml.dev/assets/index-e7Ei05G8.js:40:24283) at Ss (https://vexml.dev/assets/index-e7Ei05G8.js:40:42406)

**Comment by jaredjj3** [comment]
Good catch, I think we can fix this by adding a check [here](https://github.com/stringsync/vexml/blob/cff66f352d84ecd8102228163716250a0330fa39/src/rendering/beam.ts#L84) and making the `BeamRendering.vexflow.beam` nullable.

**Comment by rvilarl** [comment]
The cross staff meeasures are no longer there in measure 5

![image](https://github.com/stringsync/vexml/assets/22865285/dceb2fbd-d7ac-484b-aac0-ca4e9eaeb6bb)

**Comment by rvilarl** [comment]
@jaredjj3 also starting on measure 10 the second staff is missing.

![image](https://github.com/stringsync/vexml/assets/22865285/ea82dd54-9c6a-4ce0-b748-987112e2992f)

**Comment by jaredjj3** [comment]
There must be a bug with beaming. This will be a good score to thoroughly test the system.

**Comment by jaredjj3** [comment]
I'm going to take another stab at this before going back to lilypond specs. Here's what I plan to work on:

- [ ] Ensure that the top of a rendering is present.
- [ ] Prevent ties from rendering across systems.
- [ ] Investigate increasing `StaveTie` height, part distance, or both.
- [ ] Render repeats.

![vexml_dev_0_0_0 (1)](https://github.com/stringsync/vexml/assets/19232300/801ba9cc-c4e6-40d6-8c9a-8c9f824e5e0f)

**Comment by jaredjj3** [comment]
Hmm, I don't remember fixing this, but it's rendering reasonably well. @rvilarl, will you open new issues for any remaining problems? If you also have the time, it would be ideal if you could trim the MusicXML document to only include the problematic section(s).

![vexml_dev_0_0_0](https://github.com/user-attachments/assets/7aec6620-779e-4318-bd81-2246be7aa7a4)

**Comment by rvilarl** [comment]
@jaredjj3 I am planning to go back to contributing on vexml. It also seems that I could now update piano play to use vexml, right? I have a cursor and a way to get the current notes.

**Comment by jaredjj3** [comment]
That's great news! I recommend holding off until release (early Jan). I'm tightening up the public interfaces and I wouldn't want you to depend on something that changes underneath you.

**Comment by rvilarl** [comment]
Is there anything that you would like me to fix in vexfow. I want to release together with @ronyeh a new beta release in Jan?

**Comment by jaredjj3** [comment]
My biggest ask at the moment is clear font loading documentation for browser and non-browser environments.

**Comment by rvilarl** [comment]
@ronyeh above the wish from Jared

**Comment by jaredjj3** [comment]
> [@jaredjj3](https://github.com/jaredjj3) I am planning to go back to contributing on vexml. It also seems that I could now update piano play to use vexml, right? I have a cursor and a way to get the current notes.

@rvilarl you should be able to do this now. `npm install @stringsync/vexml@0.1.2`
