### ISSUE TITLE
TimeSignatures-Compound tests broken

### ISSUE THREAD

**Issue by rvilarl** [stringsync/vexml#87]
@jaredjj3 it seems that #86 has broken the compound timesignatures.

I believe that the problem is that beat should be a string and not a number

https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/beats/

**Comment by jaredjj3** [comment]
Thanks for raising this. Sorry about that. Feel free to rollback all the commits from #86 or patch a fix.
