### ISSUE TITLE
SMUFL fonts hosted by Google Fonts

### ISSUE THREAD

**Issue by rvilarl** [stringsync/vexml#89]
Hi @jaredjj3, do you know if it is possible to upload fonts to Google Foints or should we consider another CDN?

**Comment by jaredjj3** [comment]
This is the process for proposing fonts: https://github.com/google/fonts/blob/main/CONTRIBUTING.md. I don't have experience doing this, but this might be an easier sell after `vexml` increases adoption.

In the meantime, do you think it's feasible for library consumers to host the font themselves?

**Comment by rvilarl** [comment]
Thanks, and yes it is.
